version: '3'
name: elk_compose

services:
  logstash:
    image: logstash:8.6.2
    container_name: logstash
    depends_on:
      - elasticsearch
    environment:
      XPACK_MONITORING_ENABLED: "false"
      ES_HOST: "elasticsearch:9200"
    networks:
      - elk_network
    ports:
      - "5044:5044"
    volumes:
      - ./config/elk_project/logstash.conf:/config/logstash.conf:ro
    command: logstash -f /config/logstash.conf

  elasticsearch:
    image: elasticsearch:8.6.2
    container_name: elasticsearch
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms265m -Xmx265m
      xpack.security.enabled: false
      cluster.routing.allocation.disk.threshold_enabled: false
    networks:
      - elk_network
    ports:
      - 9200:9200

  kibana:
    image: kibana:8.6.2
    container_name: kibana
    networks:
      - elk_network
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      ES_JAVA_OPTS: -Xms128m -Xmx128m
    depends_on:
      - elasticsearch

networks:
  elk_network:
    name: elk_network
    driver: bridge
