# Generated by Django 3.2 on 2023-05-13 12:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20230111_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmwork',
            name='subscribe_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
