version: '3'

services:
  auth_database:
    image: postgres:13.0
    restart: always
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data/
    env_file:
      - src/core/.env.db
    command: -p 6432
    ports:
      - 6432:6432

  auth_redis:
    image: redis:latest
    restart: always
    command: --port 6381
    ports:
      - 6381:6381
    env_file:
      - src/core/.env.dev

  refresh_auth_redis:
    image: redis:latest
    restart: always
    command: --port 6380
    ports:
      - 6380:6380
    env_file:
      - src/core/.env.dev

  rate_limit_redis:
    image: redis:latest
    restart: always
    command: --port 6382
    ports:
      - 6382:6382
    env_file:
      - src/core/.env.dev

volumes:
  auth_postgres_data:
