version: '3'

services:
  service:
    image: mistandok/online-cinema-admin-panel:v1
    volumes:
      - static_volume:/opt/app/staticfiles
      - media_volume:/opt/app/mediafiles
    expose:
      - 8000
    env_file:
      - ./config/admin_panel/.env.prod
    depends_on:
      - database

  database:
    image: postgres:13.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./config/admin_panel/.env.prod.db

  etl:
      image: mistandok/online-cinema-etl-process:v2
      env_file:
        - ./config/etl_process/.env.prod
      depends_on:
        - database
        - elasticsearch
        - redis
      restart: always

  elasticsearch:
    image: elasticsearch:8.5.3
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms6g -Xmx6g
      USE_SSL: false
      xpack.security.enabled: false

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  nginx:
    image: nginx:1.19.2
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./etc/nginx/configs:/etc/nginx/conf.d:ro
      - static_volume:/opt/app/staticfiles
      - media_volume:/opt/app/mediafiles
    environment:
      NGINX_SET_REAL_IPS_FROM: "[\"192.168.1.0/24\"]"
    depends_on:
      - service
    ports:
      - 80:80

volumes:
  postgres_data:
  static_volume:
  media_volume: